spring.config.import=optional:file:.env[.properties]

spring.application.name=graph
server.port=${PORT:8080}

COGNODB_URI=${COGNODB_URI}
COGNODB_USER=${COGNODB_USER}
COGNODB_PASSWORD=${COGNODB_PASSWORD}